Ruby/PessoaEmail/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'

  get 'people' => 'pessoas#index'
  resources :emails
  resources :pessoas
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Ruby/PessoaEmail/app/models/email.rb
class Email < ApplicationRecord
  belongs_to :pessoa
end

Ruby/PessoaEmail/app/models/pessoa.rb
class Pessoa < ApplicationRecord
  # has_one :email
  # accepts_nested_attributes_for :email
end

Ruby/PessoaEmail/app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :set_email, only: [:show, :edit, :update, :destroy]

  # GET /emails
  # GET /emails.json
  def index
    @emails = Email.all
  end

  # GET /emails/1
  # GET /emails/1.json
  def show
  end

  # GET /emails/new
  def new
    @email = Email.new
    @pessoas = Pessoa.all
  end

  # GET /emails/1/edit
  def edit
    @pessoas = Pessoa.all
  end

  # POST /emails
  # POST /emails.json
  def create
    @email = Email.new(email_params)

    respond_to do |format|
      if @email.save
        format.html { redirect_to @email, notice: 'Email was successfully created.' }
        format.json { render :show, status: :created, location: @email }
      else
        format.html { render :new }
        format.json { render json: @email.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emails/1
  # PATCH/PUT /emails/1.json
  def update
    respond_to do |format|
      if @email.update(email_params)
        format.html { redirect_to @email, notice: 'Email was successfully updated.' }
        format.json { render :show, status: :ok, location: @email }
      else
        format.html { render :edit }
        format.json { render json: @email.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emails/1
  # DELETE /emails/1.json
  def destroy
    @email.destroy
    respond_to do |format|
      format.html { redirect_to emails_url, notice: 'Email was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_email
      @email = Email.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def email_params
      params.require(:email).permit(:endereco, :pessoa_id)
    end
end

Ruby/PessoaEmail/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

Ruby/PessoaEmail/app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: [:show, :edit, :update, :destroy]

  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.all
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
    # @pessoa.build_email
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully created.' }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1
  # PATCH/PUT /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa.destroy
    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: 'Pessoa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pessoa_params
      params.require(:pessoa).permit(:nome, :data_nascimento) #, email_attributes:[:id, :endereco, :pessoa_id]
    end
end

Ruby/PessoaEmail/app/helpers/emails_helper.rb
module EmailsHelper
end

Ruby/PessoaEmail/app/helpers/home_helper.rb
module HomeHelper
end

Ruby/PessoaEmail/app/helpers/pessoas_helper.rb
module PessoasHelper
  def saudacao()
    "Seja bem vindx, "+@pessoa.nome
  end
end

Ruby/PessoaEmail/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<a href="<%= pessoas_path %>">Pessoas</a></br>
<a href="<%= emails_path %>">Emails</a></br>
<%= link_to "Pessoas", pessoas_path%></br>
<%= link_to "Emails", emails_path%>

Ruby/PessoaEmail/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PessoaEmail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Ruby/PessoaEmail/app/views/pessoas/_form.html.erb
<%= form_with(model: pessoa, local: true) do |form| %>
  <% if pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
        <% pessoa.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :data_nascimento %>
    <%= form.date_select :data_nascimento, :start_year=>1900,:end_year=>2002 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Ruby/PessoaEmail/app/views/pessoas/edit.html.erb
<h1>Editing Pessoa</h1>

<%= render 'form', pessoa: @pessoa %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

Ruby/PessoaEmail/app/views/pessoas/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Home index', root_path %>

<h1>Pessoas</h1>

<table>
  <thead>
  <tr>
    <th>Id</th>
    <th>Nome</th>
    <th>Data nascimento</th>
<!--    <th>Email</th>-->
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @pessoas.each do |pessoa| %>
      <tr>
        <td><%= pessoa.id %></td>
        <td><%= pessoa.nome %></td>
        <td><%= pessoa.data_nascimento %></td>
<!--        <td><%#= pessoa.email.endereco %></td>-->
        <td><%= link_to 'Show', pessoa %></td>
        <td><%= link_to 'Edit', edit_pessoa_path(pessoa) %></td>
        <td><%= link_to 'Destroy', pessoa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pessoa', new_pessoa_path %>

Ruby/PessoaEmail/app/views/pessoas/new.html.erb
<h1>New Pessoa</h1>

<%= render 'form', pessoa: @pessoa %>
<!-- param1 Qual elemento do HTML que quero criar, no caso um formulario -->
<!-- param2  Irá redenrizar no formulários já com os inputs baseado nos atributos de pessoa -->

<%= link_to 'Back', pessoas_path %>

Ruby/PessoaEmail/app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<strong><%= saudacao() %></strong>
<p>
  <strong>Nome:</strong>
  <%= @pessoa.nome %>
</p>

<p>
  <strong>Data nascimento:</strong>
  <%= @pessoa.data_nascimento %>
</p>

<%= link_to 'Edit', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Back', pessoas_path %>